from enum import Enum

class ClubCode(Enum):
    AAL = "OKAPI AALSTAR"
    AEK = "AEK Athens"
    ALE = "Igokea Aleksandrovac"
    ALI = "Alicante"
    ALM = "OMNIWORLD ALMERE"
    ALY = "Alita Alytus"
    AMS = "Amsterdam Astronauts"
    ANR = "MoraBanc Andorra"
    ANT = "Telenet Giants Antwerp"
    APL = "Apollonas Patron"
    ARI = "Aris Thessaloniki"
    ART = "Artland Dragons"
    ASK = "ASK RIGA"
    ASV = "LDLC ASVEL Villeurbanne"
    AVE = "SS Felice Scandone"
    AVR = "AVEIRO"
    AYK = "Aykon TED Ankara Kolejliler"
    AZO = "Azovmash Mariupol"
    BAH = "Bahcesehir Koleji Istanbul"
    BAM = "Bamberger Basketball GmbH"
    BAN = "Banvit Bandirma"
    BAO = "Barons Riga"
    BAR = "FC Barcelona"
    BAS = "Baskonia Vitoria-Gasteiz"
    BBU = "Frutti Extra Bursaspor"
    BCT = "Boncourt"
    BDS = "Enel Basket Brindisi"
    BEL = "Atlas Belgrade"
    BEN = "Benfica"
    BER = "ALBA Berlin"
    BES = "Besiktas Istanbul"
    BET = "BENSTON"
    BIE = "Lauretana Biella"
    BIL = "Bilbao Basket"
    BIN = "Bree"
    BNE = "Bnei Hasharon"
    BON = "Telekom Baskets Bonn"
    BOR = "BORIK"
    BOS = "Bosna Sarajevo"
    BOU = "JL Bourg"
    BRA = "Braunschweig"
    BRE = "Brescia Leonessa"
    BRI = "Brighton Bears"
    BRT = "BREST"
    BUC = "Steaua CSM EximBank Bucharest"
    BUD = "KK Buducnost"
    BUR = "Tofas Bursa"
    CAC = "CACERES C.B."
    CAI = "Basket Zaragoza 2002 SAD"
    CAL = "Reggio Calabria"
    CAN = "Club Baloncesto Gran Canaria"
    CAS = "PEPSI CASERTA"
    CED = "KK Cedevita Zagreb"
    CHA = "Spirou Charleroi"
    CHE = "CHESTER JETS"
    CHL = "Elan Sportif Chalonnais"
    CHO = "Cholet Basket"
    CIB = "KK Cibona"
    CLU = "U-BT Cluj-Napoca"
    CNE = "CANOE JEANS"
    COL = "RheinStars Koln"
    COP = "U18 DBA Copenhagen"
    CSK = "CSKA Moscow"
    CSS = "CSKA SOFIA"
    CTU = "Pallacanestro Cantu"
    DAR = "Darussafaka Basketbol"
    DEB = "Debrecen"
    DEN = "EiffelTowers Den Bosch"
    DIJ = "JDA Dijon"
    DON = "Donetsk"
    DYN = "Dynamo Moscow"
    DYR = "Zenit St Petersburg"
    EKA = "EURAS EKATERINBURG"
    ELY = "Hapoel Gilboal Galil"
    EST = "Club Baloncesto Estudiantes"
    FAB = "FABRIANO"
    FEN = "FENERBACHE"
    FIG = "CASINO FIGUEIRA GINASIO"
    FOR = "Fortitudo Pallacanestro Bologna 103"
    FRA = "Skyliners Frankfurt"
    FRI = "Fribourg Olympic"
    FUE = "Montakit Fuenlabrada"
    GAL = "Galatasaray Spor Kulubu"
    GEI = "AVITOS GEISSEN"
    GEN = "GENEVA DEVILS"
    GIR = "Girona"
    GMU = "Swans Gmunden"
    GOE = "Goettingen"
    GOL = "GOLBEY-EPINAL"
    GRA = "BCM Gravelines Dunkerque"
    GRO = "Donar Groningen"
    GSS = "GSS Akcyjna"
    GUI = "Guildford Heat"
    HAF = "HAIFA - no usar"
    HAG = "BRANDT HAGEN"
    HAI = "Belfius Mons-Hainaut"
    HAM = "Hamburg Towers"
    HAV = "Le Havre"
    HEL = "HELIOS"
    HHN = "LEV HASHARON"
    HOP = "SAVINSKI HOPSI"
    HTA = "Hapoel Tel Aviv"
    ILI = "ILISIAKOS"
    ION = "Ionikos NF Egnatia Bank"
    IRA = "IRAKLIS"
    IRK = "IRAKLIO"
    IST = "Anadolu Efes Istanbul"
    JAE = "U18 AEK ATHENS"
    JAR = "U18 ARIS THESSALONIKI"
    JAS = "U18 LDLC ASVEL Villeurbanne"
    JAU = "U18 AUDENTES TALLINN"
    JBA = "U18 FC BARCELONA"
    JBB = "U18 BASKET BRNO "
    JBE = "U18 ALBA BERLIN"
    JBI = "U18 BANCA SELLA BIELLA"
    JBK = "U18 BARKING LONDON"
    JBO = "U18 BOSNA SARAJEVO"
    JBR = "U18 BROSE BAMBERG"
    JBS = "U18 Orange1 Bassano"
    JBU = "U18 BUDUCNOST PODGORICA"
    JBV = "U18 BEOVUK 72 BELGRADE"
    JBZ = "U18 TEAM BRAZIL"
    JCA = "U18 SEVILLE"
    JCB = "U18 CANARIAS BASKETBALL ACADEMY"
    JCE = "U18 CEDEVITA ZAGREB"
    JCH = "U18 TEAM CHINA"
    JCI = "U18 CIBONA ZAGREB"
    JCJ = "U18 U-BT CLUJ NAPOCA"
    JCS = "U18 CASERTA"
    JCT = "U18 Cholet Basket"
    JDN = "U18 DNIPRO"
    JDU = "U18 Dubai Falcons Basketball Academy"
    JEC = "U18 ELAN CHALON SUR SAONE"
    JEF = "U18 ANADOLU EFES ISTANBUL"
    JEN = "U18 TEAM ENGLAND"
    JER = "Hapoel Jerusalem Basketball Club"
    JES = "U18 MOVISTAR ESTUDIANTES"
    JFO = "U18 FORTITUDO BOLOGNA"
    JFR = "U18 BENETTON FRIBOURG "
    JGA = "U18 GALATASARAY ISTANBUL"
    JGC = "U18 GRAN CANARIA"
    JHB = "U18 Helsinki Basketball Academy"
    JHO = "U18 L'Hospitalet"
    JHT = "U18 Hapoel Yehuda Tel aviv"
    JIN = "U18 PFBB INSEP Paris"
    JJE = "U18 Hapoel Jerusalem"
    JJO = "U18 Joventut Badalona"
    JKH = "U18 Khimki Moscow Region"
    JKY = "U18 KIEV"
    JLE = "U18 LE MANS SARTHE BASKET"
    JLI = "U18 RYTAS VILNIUS"
    JLJ = "U18 CEDEVITA OLIMPIJA LJUBLJANA"
    JLK = "U18 Lietkabelis Panevezys"
    JLU = "U18  LUDWIGSBURG"
    JMA = "U18 UNICAJA MALAGA"
    JMC = "U18 AS Monaco"
    JMI = "U18 Armani Exchange Milan"
    JMM = "U18 MANDOULIDES THESSALONIKI"
    JMN = "U18 MANRESA"
    JMO = "U18 CSKA MOSCOW"
    JMR = "U18 Maroussi"
    JMU = "U18 FC BAYERN MUNICH"
    JMV = "U18 Mega MIS Belgrade"
    JNA = "U18 NANTERRE 92"
    JNI = "U18 BUDIVELNIK KIEV"
    JNY = "U18 CEZ NYMBURK"
    JOE = "U18 Overtime Elite"
    JOL = "U18 Olympiacos Piraeus"
    JOV = "Club Joventut Badalona"
    JPA = "U18 Partizan Belgrade"
    JPB = "U18 Paris Basketball"
    JPG = "U18 SC Derby Podgorica"
    JPP = "U18 Promitheas Patras"
    JPR = "U18 PRAGUE 2006"
    JPU = "U18 PAU-ORTHEZ"
    JRE = "U18 Crvena Zvezda  Belgrade"
    JRI = "U18 VEF RIGA"
    JRM = "U18 Real Madrid"
    JRO = "U18 VIRTUS ROME"
    JRU = "U18 RATIOPHARM ULM"
    JSA = "U18 Stellazzurra Rome"
    JSI = "U18 MONTEPASCHI SIENA"
    JSO = "U18 ASSECO ARKA GDYNIA"
    JSP = "U18 SPLIT CROATIA OSIGURANJE"
    JSS = "U18 SPARS SARAJEVO"
    JTB = "U18 TREVISO BASKET"
    JTE = "U18 Maccabi Tel Aviv"
    JTF = "U18 TOFAS BURSA"
    JTR = "U18 BENETTON TREVISO"
    JTS = "U18 ZPA TBILISI"
    JTV = "U18 TOPSPORTSCHOOL LEUVEN"
    JUL = "U18 FENERBAHCE ISTANBUL"
    JUR = "U18 UMANA REYER VENICE"
    JUS = "U18 USK FUTURE STARS PRAGUE"
    JVA = "U18 VALENCIA BASKET"
    JVB = "U18 VAERLOSE"
    JVC = "U18 Varese Academy"
    JVE = "U18 VENTSPILS"
    JVI = "U18 VIRTUS BOLOGNA"
    JVR = "U18 HEMOFARM VRSAC"
    JVS = "U18 VIRTUS SIENA"
    JVT = "U18 RASTA Vechta"
    JWL = "U18 SMS PZKOSZ WLADYSLAWOWO"
    JZA = "U18 Zalgiris Kaunas"
    JZD = "U18 Zadar"
    JZE = "U18 FMP BELGRADE"
    JZG = "U18 ZAGREB CROATIA OSIGURANJE"
    JZM = "U18 ZEMUN"
    JZR = "duplicado"
    JZZ = "U18 BASKET ZARAGOZA"
    KAL = "Kalev Cramo Tallinn"
    KAP = "Kapfenberg"
    KAR = "Karsiyaka"
    KEY = "MILTON KEYNES LIONS"
    KHI = "BC Khimki"
    KLA = "Neptunas Klaipeda"
    KOP = "KOPER"
    KRA = "KRASNYE KRYLIA"
    KSK = "Karsiyaka Spor Kulubu"
    KYI = "Kiev"
    LAS = "Zlatorog Lasko"
    LEM = "Le Mans Sarthe Basket"
    LEP = "FLV LEPER"
    LEU = "TELINDUS LEUVEN"
    LEV = "TSV BAYER 04 LEVERKUSEN"
    LIE = "Rytas Vilnius"
    LIG = "Euphony Liege"
    LJU = "KK Cedevita Olimpija"
    LKB = "Lietkabelis Panevezys "
    LLE = "Lleida"
    LLI = "London Lions"
    LMG = "Limoges Cercle Saint-Pierre"
    LOI = "Bisons Loimaa"
    LOK = "LOKOMOTIV ROSTOV"
    LON = "London Towers"
    LUD = "MHP RIESEN Ludwigsburg"
    LUG = "FN Lugano"
    LVK = "LEVSKI SOFIA"
    MAD = "Real Madrid"
    MAK = "Makedonikos Kozani"
    MAL = "Unicaja Malaga"
    MAR = "Maroussi BC"
    MAZ = "MAZEIKIU NAFTOS"
    MBA = "Mornar Bar"
    MCO = "AS Monaco"
    MES = "KK Krka Novo Mesto"
    MHB = "Maccabi Haifa Basketball Club"
    MIL = "EA7 Emporio Armani Milan"
    MIN = "LOKOMOTIV MINERAL VODY"
    MON = "MONTHEY "
    MOR = "LS-MORGES BASKET"
    MUN = "FC Bayern Munich"
    MUR = "UCAM Murcia"
    NAC = "NAC BREDA"
    NAH = "IRONI NAHARIYA"
    NAN = "Stade Lorrain Universite Club Nancy Basket"
    NAP = "Napoli Basket"
    NEA = "NEAR EAST"
    NEW = "NEWCASTLE EAGLES"
    NGB = "U18 Next Generation Team Belgrade"
    NGD = "U18 Next Generation Team Dubai"
    NGF = "U18 Next Generation Team Paris"
    NGG = "U18 Next Generation Team Podgorica"
    NGL = "U18 Next Generation Team Ljubljana"
    NGM = "U18 Next Generation Team Munich"
    NGP = "U18 Next Generation Team Patras"
    NGS = "U18 Next Generation Select Team"
    NGV = "U18 Next Generation Team Varese"
    NGZ = "U18 Next Generation Team Zadar"
    NIJ = "NIJMEGEN"
    NIK = "BC Budivelnyk"
    NIO = "Panionios BC"
    NOV = "BC Nizhny Novgorod"
    NTR = "Nanterre 92"
    NYM = "CEZ Basketball Nymburk"
    NYO = "NYON"
    OKT = "Volgograd"
    OLD = "Baskets Oldenburg"
    OLV = "OLIVEIRENSE"
    OLY = "Olympiacos Piraeus"
    OOS = "Basketball Club Oostende"
    OPA = "OPAVA"
    ORL = "Orleans Loiret Basket"
    OSG = "LOVCEN OSIGUR"
    OSI = "OSIGURANJE"
    OST = "DEGUSTA OSTROW"
    OVA = "Ovarense Basquetebol"
    OYA = "OYAK RENAULT"
    PAI = "Boulogne Metropolitans 92"
    PAM = "Valencia Basket"
    PAN = "Panathinaikos AKTOR Athens"
    PAO = "PAOK BC"
    PAR = "Partizan Mozzart Bet Belgrade"
    PAT = "Promitheas Patras"
    PAU = "Elan Bearnais Pau-Lacq-Orthez"
    PEM = "PBC Ural Great Perm"
    PER = "Peristeri BC"
    PES = "Scavolini Pesaro"
    PET = "Saint Petersburg Lions"
    PLL = "Panellinios Athens"
    PLO = "Ploiesti"
    PMT = "Prometey Slobozhanske"
    POR = "PORTUGAL TELECOM"
    PRS = "Paris Basketball"
    PRU = "OLD SPICE PRUSZKOW"
    QUE = "Queluz"
    RAD = "RADNICKI JUGO BEOGRAD"
    RAM = "IRONI RAMAT GAN"
    RDN = "Radnicki Kragujevac"
    RED = "Crvena Zvezda Meridianbet Belgrade"
    REG = "Grissin Bon Reggio Emilia"
    RIL = "RILSKI SPORTLIST"
    RIS = "Maccabi Rishon LeZion"
    RIV = "RIVIERA BASKET"
    ROA = "Chorale Roanne Basket"
    ROM = "Pallacanestro Virtus Roma"
    ROS = "Roseto Basket Town"
    ROY = "Pepinster"
    ROZ = "ROZH HAIN"
    RUD = "Prienai"
    SAK = "SAKALAI VILNIUS"
    SAR = "Avtodor Saratov"
    SAS = "Polisportiva Dinamo"
    SBE = "USL BENETTON TREVISO"
    SCB = "USL CBA"
    SCO = "SCOTTISH PHOENIX ROCKS"
    SEV = "Seville"
    SEX = "SEIXAL"
    SFE = "USL EUROLEAGUE"
    SFU = "USL ULEB CUP"
    SHE = "WESTFIELD SHARKS SHEFFIELD"
    SHM = "GIVAT SHMUEL"
    SIA = "Siauliai"
    SIB = "SIBENKA SIEBEN"
    SIE = "Montepaschi Siena"
    SIR = "Siroki Hercegtisak"
    SKO = "MZT Skopje Aerodrom"
    SLJ = "USL UNION OLIMPIJA LJUBLJANA"
    SLO = "GEOPLIN SLOVAN"
    SOF = "Lukoil Academic Sofia"
    SOP = "Arka Gdynia"
    SPA = "SPARTAK"
    SPL = "KK Split"
    SRM = "USL LOTTOMATICA ROMA"
    SRO = "Siroki hercegtisak"
    SRT = "SPART-MRW"
    SSP = "Spartak Saint Petersburg"
    STE = "USL MACCABI ELITE TEL AVIV"
    STR = "Strasbourg Illkirch-Graffenstaden Basket"
    SVJ = "SVJETLOST"
    SZA = "USL ZALGIRIS KAUNAS"
    SZO = "Szolnoki Olaj"
    TEL = "Maccabi Playtika Tel Aviv"
    TER = "Teramo"
    THA = "THAMES VALLEY TIGERS"
    TIK = "PETAH TIKVA"
    TIV = "Lokomotiv Kuban"
    TOR = "Fiat Turin"
    TRB = "Trabzonspor Medical Park"
    TRE = "Benetton Basket Treviso"
    TRI = "Trieste"
    TRN = "Dolomiti Energia Trento"
    TRO = "TROY PILSNER"
    TRR = "TRIER"
    TSO = "Trefl Sopot"
    TTK = "Turk Telekom Ankara"
    UDA = "U18 DARUSSAFAKA ISTANBUL"
    UDI = "Pallacanestro Udine"
    UFR = "U18 Fraport Skyliners Frankfurt"
    ULK = "Fenerbahce Beko Istanbul"
    ULM = "ratiopharm Ulm"
    UNK = "UNICS Kazan"
    UPA = "U18 Panathinaikos Athens"
    UPR = "U18 GBA PRAGUE"
    UTE = "Juventus Utena"
    UTI = "U18 Lokomotiv Kuban Krasnodar"
    VAM = "VAMA"
    VAR = "Cimberio Varese"
    VEF = "VEF Riga"
    VEN = "Ventspils"
    VER = "Scaligera Basket Verona"
    VIC = "VICHY"
    VIL = "VILVOORDE"
    VIR = "Virtus Segafredo Bologna"
    VLL = "FORUM VALLADOLID"
    VNC = "Umana Reyer Venice"
    VOJ = "VOJVODINA"
    VRS = "Hemofarm Vrsac"
    VSZ = "Alba Regia SC"
    WAR = "WARBUD POL"
    WEE = "VANILLA WEERT"
    WEV = "WEVELGEM"
    WLO = "Anwil Wloclawek"
    WOL = "BC Wolves Vilnius"
    WRO = "WKS Slask Wroclaw"
    WUE = "s.Oliver Baskets Wurzburg"
    WUR = "TSK WÜRZBURG"
    YAM = "YAMBOL"
    YUZ = "Khimik Yuzhne"
    ZAD = "KK Zadar"
    ZAG = "KK Zagreb"
    ZAL = "Zalgiris Kaunas"
    ZAS = "ZAGORJE BANKA ZASAVJE"
    ZDR = "ZDRAVLJE"
    ZEL = "FMP Belgrade"
    ZGO = "PGE Turow Zgorzelec"
    ZID = "KRASKI ZIDAR"
    ZRE = "ROGLA ZRECE"
    ZRI = "ZRINJEVAC"
    ZWO = "LANDSTEDE ZWOLLE"
    EC01 = "EuroCup Team 01"
    EC02 = "EuroCup Team 02"
    EC03 = "EuroCup Team 03"
    FT01 = "FINALIST TEAM 1"
    FT02 = "FINALIST TEAM 2"
    QF01 = "QF TEAM 1"
    QF02 = "QF TEAM 2"
    QF03 = "QF TEAM 3"
    QF04 = "QF TEAM 4"
    QF05 = "QF TEAM 5"
    QF06 = "QF TEAM 6"
    QF07 = "QF TEAM 7"
    QF08 = "QF TEAM 8"
    QRA = "Team Qualifying Round A"
    QRB = "Team Qualifying Round B"
    SF01 = "SF TEAM 1"
    SF02 = "SF TEAM 2"
    SF03 = "SF TEAM 3"
    SF04 = "SF TEAM 4"
    PIC = "Eighth-placed Team"
    PIA = "Seventh-placed Team"

class CompetitionCode(Enum):
    # AL = 'Adriatic League'
    # BE = 'Belgium League'
    # BEC = 'Belgium National Cup'
    # BU = 'Bulgarian League'
    # BUC = 'Bulgarian National Cup'
    # CR = 'Croatian League'
    # CRC = 'Croatian National Cup'
    E = 'Euroleague'
    # EN = 'English League'
    # ENC = 'English National Cup'
    # EQR = 'Euroleague Qualifying Round'
    # FR = 'French League'
    # FRC = 'French National Cup'
    # GE = 'German League'
    # GEC = 'German National Cup'
    # GR = 'Greek League'
    # GRC = 'Greek National Cup'
    # HO = 'Holand League'
    # HOC = 'Holand National Cup'
    # IS = 'Israel League'
    # ISC = 'Israel National Cup'
    # IT = 'Italian League'
    # ITC = 'Italian National Cup'
    J = 'U18 Tournament'
    # LI = 'Lithuanian League'
    # NL = 'National League'
    # PL = 'Poland League'
    # PO = 'Portugal League'
    # POC = 'Portuguese National Cup'
    # RU = 'Russian League'
    # SB = 'Serbian League'
    # SBC = 'Serbian National Cup'
    # SL = 'Slovenian League'
    # SLC = 'Slovenian National Cup'
    # SP = 'Spanish League'
    # SPC = 'Spanish National Cup'
    # SW = 'Switzerland League'
    # SWC = 'Swiitzerland National Cup'
    # TU = 'Turkish League'
    # TUC = 'Turkish League Cup'
    U = 'Eurocup'
    # S = 'ULEB Summer League'

class Stats(Enum):
    Valuation = 'Valuation'
    Score = 'Score'
    TotalRebounds = 'TotalRebounds'
    OffensiveRebounds = 'OffensiveRebounds'
    DefensiveRebounds = 'DefensiveRebounds'
    Assistances = 'Assistances'
    Steals = 'Steals'
    BlocksFavour = 'BlocksFavour'
    BlocksAgainst = 'BlocksAgainst'
    Turnovers = 'Turnovers'
    FoulsReceived = 'FoulsReceived'
    FoulsCommited = 'FoulsCommited'
    FreeThrowsMade = 'FreeThrowsMade'
    FreeThrowsAttempted = 'FreeThrowsAttempted'
    FreeThrowsPercent = 'FreeThrowsPercent'
    FieldGoalsMade2 = 'FieldGoalsMade2'
    FieldGoalsAttempted2 = 'FieldGoalsAttempted2'
    FieldGoals2Percent = 'FieldGoals2Percent'
    FieldGoalsMade3 = 'FieldGoalsMade3'
    FieldGoalsAttempted3 = 'FieldGoalsAttempted3'
    FieldGoals3Percent = 'FieldGoals3Percent'
    FieldGoalsMadeTotal = 'FieldGoalsMadeTotal'
    FieldGoalsAttemptedTotal = 'FieldGoalsAttemptedTotal'
    FieldGoalsPercent = 'FieldGoalsPercent'
    AccuracyMade = 'AccuracyMade'
    AccuracyAttempted = 'AccuracyAttempted'
    AccuracyPercent = 'AccuracyPercent'
    AssistancesTurnoversRatio = 'AssistancesTurnoversRatio'
    GamesPlayed = 'GamesPlayed'
    GamesStarted = 'GamesStarted'
    TimePlayed = 'TimePlayed'
    Contras = 'Contras'
    Dunks = 'Dunks'
    OffensiveReboundPercentage = 'OffensiveReboundPercentage'
    DefensiveReboundPercentage = 'DefensiveReboundPercentage'
    ReboundPercentage = 'ReboundPercentage'
    EffectiveFieldGoalPercentage = 'EffectiveFieldGoalPercentage'
    TrueShootingPercentage = 'TrueShootingPercentage'
    AssistRatio = 'AssistRatio'
    TurnoverRatio = 'TurnoverRatio'
    FieldGoals2AttemptedRatio = 'FieldGoals2AttemptedRatio'
    FieldGoals3AttemptedRatio = 'FieldGoals3AttemptedRatio'
    FreeThrowRate = 'FreeThrowRate'
    Possesions = 'Possesions'
    GamesWon = 'GamesWon'
    GamesLost = 'GamesLost'
    DoubleDoubles = 'DoubleDoubles'
    TripleDoubles = 'TripleDoubles'
    FieldGoalsAttempted2Share = 'FieldGoalsAttempted2Share'
    FieldGoalsAttempted3Share = 'FieldGoalsAttempted3Share'
    FreeThrowsAttemptedShare = 'FreeThrowsAttemptedShare'
    FieldGoalsMade2Share = 'FieldGoalsMade2Share'
    FieldGoalsMade3Share = 'FieldGoalsMade3Share'
    FreeThrowsMadeShare = 'FreeThrowsMadeShare'
    PointsMade2Rate = 'PointsMade2Rate'
    PointsMade3Rate = 'PointsMade3Rate'
    PointsMadeFreeThrowsRate = 'PointsMadeFreeThrowsRate'
    PointsAttempted2Rate = 'PointsAttempted2Rate'
    PointsAttempted3Rate = 'PointsAttempted3Rate'
    Age = 'Age'


class StatsMode(Enum):
    PerGame = 'PerGame'
    Accumulated = 'Accumulated'
    PerMinute = 'PerMinute'
    Per100Possesions = 'Per100Possesions'
    PerGameReverse = 'PerGameReverse'
    AccumulatedReverse = 'AccumulatedReverse'


class StatsSortMode(Enum):
    PerGame = 'PerGame'
    Accumulated = 'Accumulated'
    PerMinute = 'PerMinute'
    Per100Possesions = 'Per100Possesions'
    PerGameReverse = 'PerGameReverse'
    AccumulatedReverse = 'AccumulatedReverse'


class SeasonMode(Enum):
    Single = 'Single'
    Range = 'Range'
    All = 'All'


class SortDirection(Enum):
    Ascending = 'Ascending'
    Descending = 'Descending'

class PhaseTypeCode(Enum):
    RegularSeason = 'RS'
    FinalFour = 'FF'
    Playoffs = 'PO'
    Top16 = 'TS'